version: 2.1

workflows:
  ci:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: gradle:6.7-jdk11
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Run tests
          command: pwd
      - run:
          name: ls
          command: ls -l
      - run:
          name: whoami
          command: whoami