version: 2.1

workflows:
  ci:
    jobs:
      - build-and-test
      - approve-publish:
          type: approval
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - approve-publish
          filters:
            branches:
              only: master

jobs:
  build-and-test:
    docker:
      - image: gradle:6.7-jdk11
    steps:
      - checkout
      - run:
          name: Run tests
          command: gradle test
      - run:
          name: Build plugin
          command: gradle buildPlugin
  publish:
    docker:
      - image: gradle:6.7-jdk11
    steps:
      - checkout
      - run:
          name: Publish plugin
          command: gradle publishPlugin